spring.application.name=CRUD
spring.datasource.url=jdbc:h2:mem:linksdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.path=/h2-console
spring.messages.basename=messages,ValidationMessages
spring.messages.encoding=UTF-8
